const THINKING_MESSAGES = [
  'Revisando los números...',
  'Consultando el ERP...',
  'Déjame ver eso...',
  'Analizando datos...',
  'Dame un momento...',
  'Buscando la información...',
  'Revisando el sistema...',
  'Procesando tu solicitud...',
  'Verificando datos...',
  'Chequeando el inventario...',
  'Consultando las ventas...',
  'Cruzando datos...',
  'Mirando las cifras...',
  'Un segundo, estoy en eso...',
  'Ya casi lo tengo...',
  'Sacando los reportes...',
  'Revisando el historial...',
  'Consultando la base de datos...',
  'Calculando...',
  'Preparando el análisis...',
  'Voy a revisar eso...',
  'Extrayendo la información...',
  'Echándole un ojo a los datos...',
  'Armando el resumen...',
  'Viendo qué dicen los números...',
  'Analizando tendencias...',
  'Revisando movimientos...',
  'Consultando tasas y ventas...',
  'Buscando en el sistema...',
  'Compilando datos...',
  'Revisando el panorama...',
  'Dame unos segundos...',
  'Estoy en eso...',
  'Procesando...',
  'Evaluando la situación...',
  'Chequeando las métricas...',
  'Revisando indicadores...',
  'Viendo el estado actual...',
  'Haciendo los cálculos...',
  'Consultando fuentes...',
  'Recopilando información...',
  'Analizando el comportamiento...',
  'Sacando cuentas...',
  'Revisando patrones...',
  'Explorando los datos...',
  'Organizando la información...',
  'Juntando las piezas...',
  'Mirando el detalle...',
  'Verificando con el ERP...',
  'Revisando clientes y ventas...',
  'Haciendo el diagnóstico...',
  'Buscando patrones...',
  'Preparando respuesta...',
  'Consultando el inventario...',
  'Analizando márgenes...',
  'Revisando la rentabilidad...',
  'Chequeando el flujo de caja...',
  'Viendo los movimientos del día...',
  'Comparando períodos...',
  'Analizando la cartera...',
  'Revisando el stock...',
  'Consultando precios...',
  'Evaluando métricas...',
  'Procesando la consulta...',
  'Cruzando información...',
  'Revisando los registros...',
  'Chequeando disponibilidad...',
  'Buscando tendencias...',
  'Armando los números...',
  'Viendo qué hay...',
  'Analizando el contexto...',
  'Revisando datos recientes...',
  'Un momento, revisando...',
  'Consultando históricos...',
  'Evaluando los datos...',
  'Viendo el comportamiento...',
  'Chequeando los reportes...',
  'Preparando el informe...',
  'Revisando la operación...',
  'Buscando oportunidades...',
  'Analizando riesgos...',
  'Mirando los indicadores...',
  'Trabajando en eso...',
  'Revisando todo...',
  'Haciendo la consulta...',
  'Conectando con el ERP...',
  'Obteniendo datos frescos...',
  'Analizando el día...',
  'Chequeando la semana...',
  'Revisando el mes...',
  'Viendo los clientes...',
  'Sacando estadísticas...',
  'Mirando el rendimiento...',
  'Evaluando la operación...',
  'Consultando movimientos...',
  'Buscando en los registros...',
  'Revisando las tasas...',
  'Analizando el mercado...',
  'Viendo qué encontramos...',
  'Recolectando datos...',
  'Preparando los datos...',
  'Haciendo análisis...',
  'Revisando la información...',
];

export function getThinkingMessage(): string {
  return THINKING_MESSAGES[Math.floor(Math.random() * THINKING_MESSAGES.length)];
}
