# Stage 1: Build
FROM node:22.16-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY tsconfig.json ./
COPY src/ ./src/
COPY docs ./docs
RUN npx tsc

# Stage 2: Runtime
FROM node:22.16-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
COPY docs ./docs
CMD ["node", "dist/manager/main.js"]
